let novonumero = document.getElementById('new') // Pega o numero digitado...
let selist = document.getElementById('lista') // Pega o id do select...
let res = document.getElementById('res') // Pega o id da div de resposta...
let valores = [] //Vetor


function isNumero(n) { // Função para determinar que os numeros aceitos sejam entre 1 e 100...
    if (Number(n) >= 1 && Number(n) <= 100) {
        return true
    } else {
        return false
    }
}

function inlista(n, l) { // Função para determinar se o valor já está na lista de valores digitados...
    if (l.indexOf(Number(n)) != -1) {
        return true
    } else {
        return false
    }
}
function adicionar() { // Função para adicionar um novo valor a lista...
    if (isNumero(novonumero.value) && !inlista(novonumero.value, valores)){ // Verifica se os DOIS são verdadeiros através de sus respetivas funções...
        let nn = Number(novonumero.value) 
        valores.push(nn) // Adciona novo valor ao vetor...
        let item = document.createElement('option') // Cria um option no select...
        item.text = `Valor ${nn} adicionado.`
        selist.appendChild(item)
        res.innerHTML = ''
    } else {
        alert('valor invalido ou já encontrado na lista.')
    }
    novonumero.value = ''
    novonumero.focus() // Deixar o foco no campo...
}

function finalizar() { // Função para mostrar o resultado..  
    if (valores.length == 0) {
        alert('Adicione valores antes de finzalizar')
} else {
    let total = valores.length // Total de valores no array...
    let maior = valores[0] // Maior valor do array...
    let menor = valores[0] // Menor vaor do array...
    let soma = 0 // Variavel de soma...
    let media = 0 // Variavel de média...
    for(let pos in valores){
        soma += valores[pos] // Calculo de soma...
        media = soma / total // Calculo de média...
        if(valores[pos] > maior) // if para identificar o maior valor...
            maior = valores[pos]
        if (valores[pos] < menor) // if para identificar o menos valor....
            menor = valores[pos]
    }
    // res.innerHTML irá mostrar os resultados na tela...
    res.innerHTML = `<p>Ao todo, temos ${total} números cadastrados.</p>`
    res.innerHTML += `<p>O maior valor informado foi ${maior}.</p> `
    res.innerHTML += `<p>O menor valor informado foi ${menor}.</p> `
    res.innerHTML += `<p>Somando todos os valores, temos ${soma}.</p> `
    res.innerHTML += `<p>A média dos valores digitados é ${media}.</p>`
}
}
